package warp

import (
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net"
	"net/netip"
	"os"
	"runtime"
	"strings"
)

// ManualIdentity is user-supplied WARP WireGuard identity material.
// It is never fetched or generated by this package.
type ManualIdentity struct {
	DeviceID           string   `json:"device_id"`
	ClientID           string   `json:"client_id,omitempty"`
	Token              string   `json:"token,omitempty"`
	AccountID          string   `json:"account_id,omitempty"`
	AccountType        string   `json:"account_type,omitempty"`
	License            string   `json:"license,omitempty"`
	PrivateKey         string   `json:"private_key"`
	InterfaceAddresses []string `json:"interface_addresses"`
	PeerPublicKey      string   `json:"peer_public_key"`
	Endpoint           string   `json:"endpoint"`
	DNS                []string `json:"dns"`
	Reserved           []int    `json:"reserved,omitempty"`
}

// Identity is validated identity material persisted locally after manual import.
type Identity ManualIdentity

// ImportManualIdentity validates user-provided identity material without contacting external APIs.
func ImportManualIdentity(manual ManualIdentity) (*Identity, error) {
	clientID := strings.TrimSpace(manual.ClientID)
	reserved, err := normalizeReservedBytes(clientID, manual.Reserved)
	if err != nil {
		return nil, err
	}
	identity := Identity{
		DeviceID:           strings.TrimSpace(manual.DeviceID),
		ClientID:           clientID,
		Token:              strings.TrimSpace(manual.Token),
		AccountID:          strings.TrimSpace(manual.AccountID),
		AccountType:        strings.TrimSpace(manual.AccountType),
		License:            strings.TrimSpace(manual.License),
		PrivateKey:         strings.TrimSpace(manual.PrivateKey),
		InterfaceAddresses: trimStrings(manual.InterfaceAddresses),
		PeerPublicKey:      strings.TrimSpace(manual.PeerPublicKey),
		Endpoint:           strings.TrimSpace(manual.Endpoint),
		DNS:                trimStrings(manual.DNS),
		Reserved:           reserved,
	}
	if err := validateIdentity(identity); err != nil {
		return nil, err
	}
	return &identity, nil
}

// ImportManualIdentityFile imports a manually supplied JSON identity file and persists it securely.
func ImportManualIdentityFile(sourcePath, storePath string) (*Identity, error) {
	data, err := os.ReadFile(sourcePath)
	if err != nil {
		return nil, fmt.Errorf("read manual identity: %w", err)
	}
	var manual ManualIdentity
	if err := json.Unmarshal(data, &manual); err != nil {
		return nil, fmt.Errorf("parse manual identity: %w", err)
	}
	identity, err := ImportManualIdentity(manual)
	if err != nil {
		return nil, err
	}
	if err := SaveIdentity(storePath, *identity); err != nil {
		return nil, err
	}
	return identity, nil
}

// SaveIdentity writes identity material with restrictive permissions where the OS supports it.
func SaveIdentity(path string, identity Identity) error {
	normalized, err := ImportManualIdentity(ManualIdentity(identity))
	if err != nil {
		return err
	}
	return writeJSONSecure(path, *normalized)
}

// LoadIdentity reads and validates a securely stored identity file.
func LoadIdentity(path string) (*Identity, error) {
	if err := ensureSecureFileMode(path); err != nil {
		return nil, err
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read identity: %w", err)
	}
	var identity Identity
	if err := json.Unmarshal(data, &identity); err != nil {
		return nil, fmt.Errorf("parse identity: %w", err)
	}
	normalized, err := ImportManualIdentity(ManualIdentity(identity))
	if err != nil {
		return nil, err
	}
	return normalized, nil
}

func validateIdentity(identity Identity) error {
	if strings.TrimSpace(identity.PrivateKey) == "" {
		return errors.New("identity private key is required")
	}
	if strings.TrimSpace(identity.PeerPublicKey) == "" {
		return errors.New("identity peer public key is required")
	}
	if len(identity.InterfaceAddresses) == 0 {
		return errors.New("identity interface addresses are required")
	}
	for _, address := range identity.InterfaceAddresses {
		if _, err := netip.ParsePrefix(address); err != nil {
			return errors.New("identity interface addresses must be CIDR prefixes")
		}
	}
	if err := validateHostPort(identity.Endpoint); err != nil {
		return fmt.Errorf("identity endpoint: %w", err)
	}
	for _, dns := range identity.DNS {
		if _, err := netip.ParseAddr(dns); err != nil {
			return errors.New("identity DNS entries must be IP addresses")
		}
	}
	if _, err := validateReservedBytes(identity.Reserved); err != nil {
		return err
	}
	return nil
}

// ExtractReservedBytesFromClientID decodes a user-provided WARP client_id into WireGuard reserved bytes.
// It performs local parsing only and never contacts Cloudflare APIs.
func ExtractReservedBytesFromClientID(clientID string) ([]int, error) {
	clientID = strings.TrimSpace(clientID)
	if clientID == "" {
		return nil, errors.New("identity client_id is required")
	}
	encodings := []*base64.Encoding{
		base64.RawURLEncoding,
		base64.URLEncoding,
		base64.RawStdEncoding,
		base64.StdEncoding,
	}
	for _, encoding := range encodings {
		decoded, err := encoding.DecodeString(clientID)
		if err != nil {
			continue
		}
		if len(decoded) != 3 {
			continue
		}
		return []int{int(decoded[0]), int(decoded[1]), int(decoded[2])}, nil
	}
	return nil, errors.New("identity client_id must decode to exactly three reserved bytes")
}

func normalizeReservedBytes(clientID string, provided []int) ([]int, error) {
	reserved, err := validateReservedBytes(provided)
	if err != nil {
		return nil, err
	}
	if clientID == "" {
		return reserved, nil
	}
	derived, err := ExtractReservedBytesFromClientID(clientID)
	if err != nil {
		return nil, err
	}
	if len(reserved) == 0 {
		return derived, nil
	}
	for i := range reserved {
		if reserved[i] != derived[i] {
			return nil, errors.New("identity reserved bytes must match client_id")
		}
	}
	return reserved, nil
}

func validateReservedBytes(values []int) ([]int, error) {
	if len(values) == 0 {
		return nil, nil
	}
	if len(values) != 3 {
		return nil, errors.New("identity reserved bytes must contain exactly three byte values")
	}
	normalized := make([]int, len(values))
	for i, value := range values {
		if value < 0 || value > 255 {
			return nil, errors.New("identity reserved bytes must be in the range 0-255")
		}
		normalized[i] = value
	}
	return normalized, nil
}

func validateHostPort(address string) error {
	if strings.TrimSpace(address) == "" {
		return errors.New("is required")
	}
	_, port, err := net.SplitHostPort(address)
	if err != nil {
		return errors.New("must be host:port")
	}
	if port == "" || port == "0" {
		return errors.New("must include a non-zero port")
	}
	return nil
}

func writeJSONSecure(path string, value any) error {
	data, err := json.MarshalIndent(value, "", "  ")
	if err != nil {
		return fmt.Errorf("marshal identity: %w", err)
	}
	data = append(data, '\n')
	if err := writeSecureFileAtomic(path, data); err != nil {
		return fmt.Errorf("write secure JSON file: %w", err)
	}
	return nil
}

func ensureSecureFileMode(path string) error {
	if runtime.GOOS == "windows" {
		return nil
	}
	info, err := os.Lstat(path)
	if err != nil {
		return fmt.Errorf("stat secure file: %w", err)
	}
	if info.Mode()&os.ModeSymlink != 0 {
		return fmt.Errorf("refuse to load symlink: %s", path)
	}
	if info.Mode().Perm()&0o077 != 0 {
		return fmt.Errorf("identity file permissions for %s are too open (%04o); chmod 600 %s before loading", path, info.Mode().Perm(), path)
	}
	return nil
}

func trimStrings(values []string) []string {
	trimmed := make([]string, 0, len(values))
	for _, value := range values {
		value = strings.TrimSpace(value)
		if value != "" {
			trimmed = append(trimmed, value)
		}
	}
	return trimmed
}
